name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:    
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Server
        run: |
          ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.SERVER_IP }}
          cd python-Subscription-api
          git pull origin main
